name: Check on PR
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened, reopened ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
      - name: 'Setup Prerequisites'
        uses: ./.github/actions/setup-prerequisites

      - name: 'Run static analysis'
        shell: bash
        run: |
          ./gradlew --no-daemon \
            :kboy-lib:staticAnalysis \
            :kboy-benchmark:staticAnalysis \
            :kboy-shared:staticAnalysis \
            :kboy:android:staticAnalysis \
            :kboy:desktop:staticAnalysis \
            :kboy:web:staticAnalysis

      - name: 'Run tests'
        shell: bash
        run: |
          ./gradlew --no-daemon :kboy-lib:jvmTest
