name: Check on PR
on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [ opened, reopened ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
      - name: 'Setup Prerequisites'
        uses: ./.github/actions/setup-prerequisites

      - name: 'Run detekt'
        shell: bash
        run: |
          ./gradlew --no-daemon --stacktrace :kboy-lib:detekt :kboy-lib:detektAndroidMain :kboy-lib:detektJvmMain :kboy-lib:detektJvmTest :kboy-lib:detektIosArm64Main :kboy-lib:detektIosArm64Test :kboy-lib:detektWasmJsMain :kboy-lib:detektWasmJsTest

      - name: 'Run tests'
        shell: bash
        run: |
          ./gradlew --no-daemon --stacktrace :kboy-lib:jvmTest
