name: Deploy KBoy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6
      - name: 'Setup Prerequisites'
        uses: ./.github/actions/setup-prerequisites
      - name: 'Build web'
        run: ./gradlew :kboy-lib:wasmJsBrowserDistribution
      - name: 'Configure GitHub Pages'
        uses: actions/configure-pages@v5
      - name: 'Upload artifact'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./kboy-lib/build/dist/wasmJs/productionExecutable
      - name: 'Deploy'
        uses: actions/deploy-pages@v4
