name: Publish internal
on:
  push:
    branches:
      - 'main'

jobs:
  publish-android:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Prepare secrets
      env:
        FASTLANE_GOOGLE_PLAY_KEY_FILE: ${{ secrets.FASTLANE_GOOGLE_PLAY_KEY_FILE }}
        ANDROID_RELEASE_KEYSTORE_PROPERTIES_FILE: ${{ secrets.ANDROID_RELEASE_KEYSTORE_PROPERTIES_FILE }}

      run: |
        echo "$FASTLANE_GOOGLE_PLAY_KEY_FILE" >> ./keystore/android/fastlane-google-play-key.json
        echo "$ANDROID_RELEASE_KEYSTORE_PROPERTIES_FILE" >> ./keystore/android/keystore.properties
        
    - name: Run Fastlane
      working-directory: ./composeApp
      run: fastlane internal_testing